---
- name: nginx installation
  ansible.builtin.apt:
    update_cache: true
    name: nginx
    state: present

- name: copy nginx config from template
  ansible.builtin.template:
    src: 'site.conf.j2'
    dest: '/etc/nginx/conf.d/site-{{ item }}.conf'
    owner: root
    group: root
    mode: '0664'
  loop: '{{ sites }}'
  notify: restart nginx

- name: items location
  ansible.builtin.file:
    path: '/var/www/{{ item }}/'
    state: directory
    mode: '0755'
  loop: '{{ sites }}'

- name: copy index from my dudes
  ansible.builtin.template:
    src: 'index.html.j2'
    dest: '/var/www/{{ item }}/index.html'
    force: true
    owner: root
    group: root
    mode: '0644'
  loop: '{{ sites }}'
